[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"  # Set to "false" if you want to ignore warnings during build

[functions]
  node_bundler = "esbuild"
  [functions.timeout]
    default = 10

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://identity.netlify.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://*.googleapis.com https://api.deepseek.com; frame-src 'self'"
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# If you have a separate app in the /app subdirectory, uncomment the following:
# [[redirects]]
#   from = "/app/*"
#   to = "/app/index.html"
#   status = 200
