# Netlify Build Configuration
[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"

# Netlify Functions Configuration
[functions]
  # The directory path should match the folder structure.
  directory = "netlify/functions" 
  node_bundler = "esbuild"
  # External modules configuration removed for HTTP function
  # external_node_modules = ["firebase-admin"]

# HTTP function configuration (not scheduled)
[functions."ai-proxy"]
  # schedule = "*/5 * * * *"  # Disabled - this is an HTTP function
  # Increased to 30s to allow for AI API response times and retries.
  timeout = 30

# API Proxy Rewrite Rule
# This rule makes the function available at a cleaner URL (e.g., /api/ai-proxy).
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Header rules for aggressive asset caching
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimized headers for serverless functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, max-age=0"
    Connection = "keep-alive"
    Keep-Alive = "timeout=10"
    Access-Control-Allow-Origin = "*"

# Node.js 22 production configuration
[context.production]
  [context.production.environment]
    AWS_LAMBDA_JS_RUNTIME = "nodejs22.x"
    NODE_OPTIONS = "--enable-source-maps --max-http-header-size=16384"

