# Build settings for a function-only deployment.
# We don't need a build command or publish directory.
[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Global function settings
[functions]
  node_bundler = "esbuild"
  # The global timeout is removed from here

# Specific configuration for the "ai-proxy" function
[functions."ai-proxy"]
  timeout = 20 # Timeout is now set only on the specific function


# Security headers for your API endpoint
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rule to make your function available at a clean URL
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/ai-proxy/:splat"
  status = 200