# ==============================================================================
# Netlify Configuration File
# ==============================================================================

[build]
  command = "npm install && cd netlify/functions && npm install && cd ../../ && npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  [functions.timeout]
    default = 9.5

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-sitemap"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://*.googleapis.com https://api.deepseek.com https://www.google-analytics.com https://ssl.google-analytics.com; frame-src 'self' https://app.netlify.com; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self'"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/ai-proxy"
  to = "/.netlify/functions/ai-proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200