[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  timeout = 10

# Per-function configuration
[[functions]]
  path = "ai-proxy.js"
  timeout = 20

[prerendering]
  enable = true
  cache_control = "public, max-age=3600"
  include = ["/*"]
  exclude = ["/admin/*", "/api/*", "/.netlify/functions/*"]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://identity.netlify.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://*.googleapis.com https://api.deepseek.com; frame-src 'self'"

# Plugins
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    baseUrl = "https://promptmakers.app"

# Edge Handlers
[build.edge_handlers]
  directory = "edge-handlers"