backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "prompts"
    label: "Prompts"
    folder: "src/content/prompts"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "template", label: "Prompt Template", widget: "text" }
      - { name: "category", label: "Category", widget: "string" }
