# This file tells Netlify how to build your project.
# It should be at the very top level (root) of your GitHub repository.

[build]
  # Set the base directory to the folder that contains your React app.
  base = "prompt-studio-app"

  # The command to build your site. Netlify will run this inside the base directory.
  command = "npm run build"

  # The directory to publish after the build is complete.
  # This is also relative to the base directory.
  publish = "build"